sudo: false

cache:
    directories:
        - $HOME/.composer

git:
    depth: 1

language: php

before_install:
    - composer self-update
    - phpenv config-rm xdebug.ini || return 0
    - composer global show hirak/prestissimo -q || composer global require hirak/prestissimo

matrix:
    include:
        - name: PHP 7.2
          php: '7.2'
          install: composer update
        - name: PHP 7.3
          php: '7.3'
          install: composer update
          after_script:
              - php vendor/bin/coveralls -v

script:
    - vendor/bin/php-cs-fixer fix --diff --dry-run -v
    - vendor/bin/phpunit
